# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    password:

#端口号
server:
  port: 8081

markerhub:
  jwt:
    secret: test
    expire: 3600


#Mybatis映射文件
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
