# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8081

markerhub:
  jwt:
    secret: test
    expire: 3600
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
